### ISSUE TITLE
Support I2C

### ISSUE THREAD

**Issue by orztrickster** [rdagger/micropython-ssd1309#3]
Is there a way for this to support I2C?

**Comment by rdagger** [comment]
You would need to modify the class constructor to accept and I2C parameter.
Then you would need to modify the write_cmd and write_data for I2C.  That should work although I have not tried.
SPI will provide better performance than I2C.

**Comment by Omid888** [comment]
first I need to thank you for your good work. second I need to request about the I2C driver as well. Since you don't seem to have a plan for adding this feature, can you please provide more details about it? I tried to change the constructor and write_cmd and write_data but found no luck.
P.S: This repo also was my reference too ([Link](https://github.com/stlehmann/micropython-ssd1306/tree/master))
